name: Cross Browser Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache Python dependencies to speed up the workflow
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update system and install browsers
        run: |
          # Update system packages
          sudo apt-get update
          sudo apt-get upgrade -y

          # Install required dependencies
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4

          # Install Chrome
          wget -q "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
          sudo dpkg -i google-chrome-stable_current_amd64.deb || true
          sudo apt-get install -f -y

          # Install Edge
          wget -q "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_120.0.2210.91-1_amd64.deb"
          sudo dpkg -i microsoft-edge-stable_120.0.2210.91-1_amd64.deb || true
          sudo apt-get install -f -y

          # Install Firefox
          sudo apt-get install -y firefox

      - name: Install WebDrivers
        run: |
          # Create directory for WebDrivers
          mkdir -p /usr/local/bin

          # Chrome WebDriver
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}" -O chrome_version.txt
          CHROMEDRIVER_VERSION=$(cat chrome_version.txt)
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
          unzip -o chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

          # Edge WebDriver
          wget -q "https://msedgedriver.azureedge.net/LATEST_STABLE" -O edge_version.txt
          EDGEDRIVER_VERSION=$(cat edge_version.txt)
          wget -q "https://msedgedriver.azureedge.net/${EDGEDRIVER_VERSION}/edgedriver_linux64.zip" -O edgedriver.zip
          unzip -o edgedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/msedgedriver

          # Firefox WebDriver (GeckoDriver)
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz" -O geckodriver.tar.gz
          tar -xzf geckodriver.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver

          # Yandex WebDriver
          wget -q "https://repo.yandex.ru/webdriver/yandexdriver-linux-latest.zip" -O yandexdriver.zip
          unzip -o yandexdriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/yandexdriver

      - name: Run tests with Xvfb
        run: |
          mkdir -p allure-results
          xvfb-run -a BROWSER=chrome python crossbrowsertests.py
          xvfb-run -a BROWSER=yandex python crossbrowsertests.py
          xvfb-run -a BROWSER=edge python crossbrowsertests.py
          xvfb-run -a BROWSER=firefox python crossbrowsertests.py

      - name: Generate Allure Report
        run: |
          wget -qO allure.tar.gz https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          tar -xzf allure.tar.gz
          ./allure-2.17.2/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
