name: Cross Browser Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install browsers and WebDrivers
        run: |
          # Install Chrome
          sudo apt-get update && sudo apt-get install -y google-chrome-stable
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" -O chrome_version.txt
          CHROMEDRIVER_VERSION=$(cat chrome_version.txt)
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

          # Install Edge
          wget -q "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_120.0.2210.91-1_amd64.deb"
          sudo dpkg -i microsoft-edge-stable_120.0.2210.91-1_amd64.deb || sudo apt-get -f install -y
          wget -q "https://msedgedriver.azureedge.net/120.0.2210.91/edgedriver_linux64.zip"
          unzip edgedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/msedgedriver

          # Install Firefox
          sudo apt-get update && sudo apt-get install -y firefox-esr
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz"
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver

          # Install Yandex
          wget -q "https://github.com/yandex/yandex-tank/releases/download/v2.1.0/yandex-tank-2.1.0-linux-amd64.tar.gz"
          tar -xzf yandex-tank-2.1.0-linux-amd64.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/yandexdriver

      - name: Run tests in Chrome
        run: |
          mkdir -p allure-results
          BROWSER=chrome pytest crossbrowsertests.py --alluredir=allure-results

      - name: Run tests in Edge
        run: |
          mkdir -p allure-results
          BROWSER=edge pytest crossbrowsertests.py --alluredir=allure-results

      - name: Run tests in Firefox
        run: |
          mkdir -p allure-results
          BROWSER=firefox pytest crossbrowsertests.py --alluredir=allure-results

      - name: Run tests in Yandex
        run: |
          mkdir -p allure-results
          BROWSER=yandex pytest crossbrowsertests.py --alluredir=allure-results

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: '*.png'

      - name: Generate Allure Report
        run: |
          wget -qO allure.tar.gz https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          tar -xzf allure.tar.gz
          ./allure-2.17.2/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
