name: Cross Browser Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache Python dependencies to speed up the workflow
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install browsers
        run: |
          # Install Chrome
          wget -q "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          # Checking Chrome installation
          google-chrome-stable --version

          # Install Edge
          wget -q "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_120.0.2210.91-1_amd64.deb"
          sudo dpkg -i microsoft-edge-stable_120.0.2210.91-1_amd64.deb || sudo apt-get -f install -y
          # Checking Edge installation
          microsoft-edge --version

      - name: Install WebDrivers
        run: |
          echo "Creating directory for WebDrivers"
          mkdir -p /usr/local/bin

          # Chrome WebDriver
          echo "Fetching Chrome version"
          CHROME_VERSION=$(google-chrome --version 2>/dev/null | cut -d ' ' -f 3 | cut -d '.' -f 1)

          if [ -z "$CHROME_VERSION" ]; then
            echo "Chrome is not installed or version retrieval failed. Installing Chrome."
            wget -q "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
            CHROME_VERSION=$(google-chrome --version 2>/dev/null | cut -d ' ' -f 3 | cut -d '.' -f 1)
          fi

          echo "Chrome version: ${CHROME_VERSION}"

          # Fetch the ChromeDriver version based on Chrome version
          if [ -z "$CHROME_VERSION" ]; then
            echo "Error: Failed to retrieve Chrome version."
            exit 1
          fi

          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}" -O chrome_version.txt
          if [ $? -ne 0 ]; then
            echo "Failed to fetch ChromeDriver version for Chrome ${CHROME_VERSION}. Check your network or the availability of the service."
            exit 1
          fi

          CHROMEDRIVER_VERSION=$(cat chrome_version.txt)
          echo "ChromeDriver version: ${CHROMEDRIVER_VERSION}"

          # Download and extract ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download ChromeDriver version ${CHROMEDRIVER_VERSION}. Check network or service availability."
            exit 1
          fi
          unzip -o chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver || { echo 'Failed to chmod ChromeDriver'; exit 1; }

          # Edge WebDriver
          echo "Fetching Edge version"
          EDGE_VERSION=$(wget -qO- "https://msedgedriver.azureedge.net/LATEST_STABLE")

          if [ -z "$EDGE_VERSION" ]; then
            echo "Edge version retrieval failed."
            exit 1
          fi

          echo "EdgeDriver version: ${EDGE_VERSION}"
          wget -q "https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip" -O edgedriver.zip || { echo 'Failed to fetch EdgeDriver'; exit 1; }
          unzip -o edgedriver.zip -d /usr/local/bin/ || { echo 'Failed to unzip EdgeDriver'; exit 1; }
          chmod +x /usr/local/bin/msedgedriver || { echo 'Failed to chmod EdgeDriver'; exit 1; }

      - name: Run tests with Xvfb
        run: |
          mkdir -p allure-results
          BROWSER=chrome python crossbrowsertests.py

      - name: Generate Allure Report
        run: |
          wget -qO allure.tar.gz https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          tar -xzf allure.tar.gz
          ./allure-2.17.2/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
