name: Cross Browser Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_chrome:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in Chrome
        run: |
          mkdir -p allure-results
          BROWSER=chrome python crossbrowsertests.py --alluredir=allure-results

      - name: Upload Allure results for Chrome
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-chrome
          path: allure-results/

  test_edge:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-edge:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in Edge
        run: |
          mkdir -p allure-results
          BROWSER=edge pytest crossbrowsertests.py --alluredir=allure-results

      - name: Upload Allure results for Edge
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-edge
          path: allure-results/

  generate_report:
    needs: [test_chrome, test_edge]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          path: allure-results

      - name: Generate Allure report
        run: |
          wget -q0 allure.tar.gz https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          tar -xzf allure.tar.gz
          ./allure-2.17.2/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
